name: DietMicrobeNet Unit Testing 
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  host_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: DietMicrobeNet
          environment-file: environment.yaml
      - run: |
          pip install -e .
          cd src/tests/
          python -m unittest test_Host

  dietmicrobe_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: DietMicrobeNet
          environment-file: environment.yaml
      - run: |
          pip install -e .
          cd src/tests/
          python -m unittest test_DietMicrobe

  dm_graphcomparison_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: DietMicrobeNet
          environment-file: environment.yaml
      - run: |
          pip install -e .
          cd src/tests/
          python -m unittest test_DMGraphComparison

  host_graphcomparison_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: DietMicrobeNet
          environment-file: environment.yaml
      - run: |
          pip install -e .
          cd src/tests/
          python -m unittest test_HostGraphComparison